### ISSUE TITLE
"NoMethodError: undefined method `each' for nil:NilClass" in formatmetrics()

### ISSUE THREAD

**Issue by jhotta** [DataDog/documentation#1209]
If we forget to add "git_integration_title: xxxxx" or miss spell, we get the below error message.  We need to add more message to know where the issue originate. 

---
Adding just `<%= get_metrics_from_git() %>` line to a content brakes HTML compilation with the following  method error.

```
Captain! We’ve been hit!

Message:

NoMethodError: undefined method `each' for nil:NilClass

Compilation stack:

  - [item]   /ja/integrations/expressjs/ (rep default)

Stack trace:

  0. lib/helpers_.rb:230:in `formatmetrics'
  1. lib/helpers_.rb:224:in `get_metrics_from_git'
  2. item /ja/integrations/expressjs/ (rep default):17:in `get_binding'
  3. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
  4. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
  5. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanoc-3.8.0/lib/nanoc/filters/erb.rb:33:in `run'
  6. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanoc-3.8.0/lib/nanoc/base/compilation/filter.rb:117:in `setup_and_run'
  7. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanoc-3.8.0/lib/nanoc/base/result_data/item_rep.rb:343:in `filter'
  8. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanoc-3.8.0/lib/nanoc/base/compilation/item_rep_proxy.rb:45:in `filter'
  9. /Users/papago/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/nanoc-3.8.0/lib/nanoc/base/compilation/rule_context.rb:59:in `filter'
  ... 42 more lines omitted. See full crash log for details.
```

**Comment by l0k0ms** [comment]
Hello, 

We changed the framework from nanoc to hugo, This issue is now deprecated. 
Thanks for the feedback :)

Best,
