### ISSUE TITLE
etcd datadog integration throws error: Unable to find prometheus URL in config file.

### ISSUE THREAD

**Issue by spratt** [DataDog/documentation#6765]
**Describe the bug**
etcd integration with datadog-agent complains that it is unable to find prometheus URL in config file.

**To Reproduce**
1. Run datadog agent version `Agent 7.16.1 - Commit: 02e0969 - Serialization version: 4.15.0 - Go version: go1.12.9` in kubernetes.
2. Run bitnami/etcd:3.4.3-ol-7-r115 (`etcdctl version: 3.4.3, API version: 3.4`) in kubernetes.
3. Follow the instructions on https://docs.datadoghq.com/integrations/etcd/#configuration and add the following annotations to the etcd kubernetes configuration:
```
    annotations:
        ad.datadoghq.com/etcd.check_names: '["etcd"]'
        ad.datadoghq.com/etcd.init_configs: '[{}]'
        ad.datadoghq.com/etcd.instances: '[{"url": "http://%%host%%:2379"}]'
```
4. Get a prompt on the pod running the datadog agent: `kubectl exec -it datadog-agent-pod-name -- /bin/bash`
5. Watch the tail of the agent logs: `tail -f /var/log/datadog/agent.log` for the following error:
```
2020-02-25 21:37:42 UTC | CORE | ERROR | (pkg/collector/python/loader.go:224 in addExpvarConfigureError) | py.loader: could not configure check 'etcd (2.1.0)': could not invoke 'etcd' python check constructor. New constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/etcd/etcd.py", line 100, in __init__
    default_namespace='etcd',
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 70, in __init__
    self.get_scraper_config(instance)
  File "/opt/datadog-agent/embedded/lib/python3.7/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 88, in get_scraper_config
    raise CheckException("Unable to find prometheus URL in config file.")
datadog_checks.base.errors.CheckException: Unable to find prometheus URL in config file.
```

**Expected behavior**
I expect the following log messages:
```
2020-02-26 00:13:42 UTC | CORE | INFO | (pkg/collector/scheduler/scheduler.go:77 in Enter) | Scheduling check etcd with an interval of 15s
2020-02-26 00:13:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:261 in work) | Running check etcd
2020-02-26 00:13:43 UTC | CORE | INFO | (pkg/collector/runner/runner.go:327 in work) | Done running check etcd
```

**Fix**
I know that the above is the expected behavior because I have found that using the following annotations fixes the problem:
```
      annotations:
        ad.datadoghq.com/etcd.check_names: '["etcd"]'
        ad.datadoghq.com/etcd.init_configs: '[{}]'
        ad.datadoghq.com/etcd.instances: |
          [{
            "url": "http://%%host%%:2379",
            "prometheus_url": "http://%%host%%:2379/metrics"
          }]
```

**Comment by l0k0ms** [comment]
Hello, 

Many thanks for this feedback ! i've went ahead and opened a PR to fix this documentation. 
I'm going to close this issue for now, but if you have other feedback or question feel free to re-open it or open a new issue !

Best,
Pierre
